apiVersion: v1
kind: Service
metadata:
  name: vrijmibips
  labels:
    app: vrijmibips
spec:
  selector:
    app: vrijmibips
  ports:
    - name: metrics
      protocol: TCP
      port: 8000
      targetPort: metrics
